# Change these first
owner: albertoferro # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Dealmaker
    url: https://app.dealmaker.tech/
  - name: Sataging
    url: https://staging.dealmaker-dev.com
assignees: # Users to assign downtime issues (optional)
  - albertoferro
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://cdn2.hubspot.net/hub/7493765/hubfs/DealMaker%20Logo%20Dark.png?height=120&name=DealMaker%20Logo%20Dark.png
  name: Status Page
  introTitle: "*powered entirely by GitHub."
  introMessage: "Status Page from Alberto Ferro"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
