# Change these first
owner: albertoferro # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Dev1
    url: https://dev1.dealmaker-dev.com
  - name: Dev2
    url: https://dev2.dealmaker-dev.com
  - name: Dev 3
    url: https://dev3.dealmaker-dev.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
assignees: # Users to assign downtime issues (optional)
  - albertoferro
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status Page
  introTitle: "*powered entirely by GitHub."
  introMessage: "Status Page from Alberto Ferro"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
